/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import javax.swing.ButtonGroup;





/**
 *
 * @author mohamed zidan
 */
public class Home extends javax.swing.JFrame {

    private int bool;

   
  

    /**
     * Creates new form library2
     */
   
    public Home() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
     
     groupButtons();
    Departement.setEnabled(false);
    Customers.setEnabled(false);
       jLabel4.setEnabled(false); 
jLabel3.setEnabled(false); 
    }
    
   public void groupButtons(){
       ButtonGroup gb=new ButtonGroup ();
       gb.add(Customers);
       gb.add(Departement);
       gb.add(Supplier);
   }
  
public void setlabel(String s){
    jLabel2.setText(s);
}
    public void setclick(int x) {
        this.bool = x;
    }

    public int getclick() {
        return bool;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Supplier = new javax.swing.JRadioButton();
        Departement = new javax.swing.JRadioButton();
        Customers = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");

        jPanel1.setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButton1.setText("GO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(470, 680, 100, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("                     ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(210, 20, 170, 80);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Books");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(410, 290, 160, 70);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Employees");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 520, 160, 60);

        Supplier.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Supplier.setText("          Supplier");
        Supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierActionPerformed(evt);
            }
        });
        jPanel1.add(Supplier);
        Supplier.setBounds(210, 210, 170, 70);

        Departement.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Departement.setText("       Departement");
        Departement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartementActionPerformed(evt);
            }
        });
        jPanel1.add(Departement);
        Departement.setBounds(210, 443, 170, 60);

        Customers.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Customers.setText("        Customers");
        Customers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomersActionPerformed(evt);
            }
        });
        jPanel1.add(Customers);
        Customers.setBounds(210, 665, 160, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/Untitled.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -10, 580, 770);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomersActionPerformed
        setclick(3);        // TODO add your handling code here:
    }//GEN-LAST:event_CustomersActionPerformed

    private void DepartementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartementActionPerformed
        setclick(2);         // TODO add your handling code here:
    }//GEN-LAST:event_DepartementActionPerformed

    private void SupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierActionPerformed
        setclick(1);         // TODO add your handling code here:
    }//GEN-LAST:event_SupplierActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        switch (getclick()) {

            case 1:
            Suppliers.S.setVisible(true);
            
            Departement.setEnabled(true);
            jLabel3.setEnabled(true); 
            dispose();
            break;
            case 2:
            Suppliers.D.setVisible(true);
         
            Customers.setEnabled(true);
            jLabel4.setEnabled(true); 
            dispose();
            break;
            case 3:
            Suppliers.C.setVisible(true);
           
            dispose();
            break;

            default:

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
                

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Customers;
    private javax.swing.JRadioButton Departement;
    private javax.swing.JRadioButton Supplier;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
