/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Entitites.*;
import Tables.TabelModel;
import Tables.TabelModel3;
import Tables.TableFunctions;
import static javax.swing.ListSelectionModel.SINGLE_SELECTION;

/**
 *
 * @author Raffy
 */
public class IndCustomer extends javax.swing.JFrame {

    private String[] sNames = new String[Library.department.size()];
    int i;
    Customer c;

    public IndCustomer(int i) {
        initComponents();
setLocationRelativeTo(null);
        setResizable(false);
        
        combobooks.setModel(new javax.swing.DefaultComboBoxModel());
           combodepartement.setModel(new javax.swing.DefaultComboBoxModel());
        combodepartement.setVisible(false);
        combobooks.setVisible(false);
        saveButton.setVisible(false);
        copiesfield.setVisible(false);
        departementlabel.setVisible(false);
        booklabel.setVisible(false);
copieslabel1.setVisible(false);
        for (int x = 0; x < Library.department.size(); x++) {
            sNames[x] = Library.department.get(x).getName();
        }

        combodepartement.setModel(new javax.swing.DefaultComboBoxModel(sNames));

        this.i = i;
        c = Library.customer.get(i);

        updateTable(c);

        jTable1.setSelectionMode(SINGLE_SELECTION);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        combodepartement = new javax.swing.JComboBox<>();
        copiesfield = new javax.swing.JTextField();
        combobooks = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        saveButton = new javax.swing.JButton();
        addBookButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        departementlabel = new javax.swing.JLabel();
        booklabel = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        home = new javax.swing.JButton();
        copieslabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Add Books To Customer");
        setLocation(new java.awt.Point(0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        combodepartement.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combodepartement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combodepartementActionPerformed(evt);
            }
        });

        combobooks.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combobooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobooksActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Price", "Serial", "Number of Copies"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        addBookButton.setText("Add");
        addBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Books To Customer");

        departementlabel.setText("Choose Departement");

        booklabel.setText("Choose A Book");

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        copieslabel1.setBackground(new java.awt.Color(255, 51, 51));
        copieslabel1.setForeground(new java.awt.Color(255, 51, 51));
        copieslabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        copieslabel1.setText("*that Number of copies is out of stock");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(addBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(departementlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combodepartement, 0, 181, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(combobooks, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(copiesfield, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(booklabel, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                .addGap(15, 15, 15))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(copieslabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(departementlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                    .addComponent(booklabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combobooks, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBookButton)
                    .addComponent(combodepartement, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(copiesfield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(copieslabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void updateTable(Customer c, Book b) {
       TabelModel3 model = TableFunctions.updateBookofCustTable(c, b);
       jTable1.setModel(model);
       Library.customer.set(i, c);
   }

   void updateTable(Customer c) {
       TabelModel3 model = TableFunctions.updateBookofCustTable(c);
       jTable1.setModel(model);
       Library.customer.set(i, c);
   }

    private void addBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookButtonActionPerformed
        combodepartement.setVisible(true);
        combobooks.setVisible(true);

       
        copiesfield.setVisible(true);
        departementlabel.setVisible(true);
        booklabel.setVisible(true);
        saveButton.setVisible(true);

    }//GEN-LAST:event_addBookButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        Book b;
        int indexOfBook = combobooks.getSelectedIndex();
        int indexOfDepartment = combodepartement.getSelectedIndex();
        b = Library.department.get(indexOfDepartment).book.get(indexOfBook);
        int availableCopies = b.getNumberOfCopies();
        int orderedCopies;
        if (copiesfield.getText() != null) {// raffy helppppppp.
            orderedCopies = Integer.parseInt(copiesfield.getText());
        } else {
            orderedCopies = 1;
        }
        if(orderedCopies > availableCopies) {
           copieslabel1.setVisible(true);
            b.setNumberOfCopies(availableCopies);
            Library.department.get(indexOfDepartment).deleteBook(indexOfBook);
            System.out.println("dsfadsfsdssfsaf");
        }
                else if (orderedCopies == availableCopies) {
            b.setNumberOfCopies(orderedCopies);
            Library.department.get(indexOfDepartment).deleteBook(indexOfBook);
            
        } else {
            b.setNumberOfCopies(orderedCopies);
            Library.department.get(indexOfDepartment).book.get(indexOfBook).setNumberOfCopies(availableCopies - orderedCopies);

        }

        updateTable(c, b);
        combodepartement.setVisible(false);
        combobooks.setVisible(false);
        saveButton.setVisible(false);
        copiesfield.setVisible(false);
        departementlabel.setVisible(false);
        booklabel.setVisible(false);
copieslabel1.setVisible(false);
  for (int x = 0; x < Library.department.size(); x++) {
            sNames[x] = Library.department.get(x).getName();
        }

        combodepartement.setModel(new javax.swing.DefaultComboBoxModel(sNames));
copiesfield.setText("");
combobooks.setModel(new javax.swing.DefaultComboBoxModel());
    }//GEN-LAST:event_saveButtonActionPerformed

    private void combodepartementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combodepartementActionPerformed
        int i = combodepartement.getSelectedIndex();
        String[] sName = new String[Library.department.get(i).book.size()];
        for (int x = 0; x < Library.department.get(i).book.size(); x++) {
            if (Library.department.get(i).book.get(x).getNumberOfCopies() != 0) {
                sName[x] = Library.department.get(i).book.get(x).getName();// TODO add your handling code here:
    }//GEN-LAST:event_combodepartementActionPerformed
            combobooks.setModel(new javax.swing.DefaultComboBoxModel(sName));
        }
    }
    private void combobooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobooksActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_combobooksActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
combodepartement.setVisible(false);
        combobooks.setVisible(false);
        saveButton.setVisible(false);
        copiesfield.setVisible(false);
        departementlabel.setVisible(false);
        booklabel.setVisible(false);
copieslabel1.setVisible(false);
        Suppliers.h.setVisible(true);
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
combodepartement.setVisible(false);
        combobooks.setVisible(false);
        saveButton.setVisible(false);
        copiesfield.setVisible(false);
        departementlabel.setVisible(false);
        booklabel.setVisible(false);
copieslabel1.setVisible(false);
        Suppliers.C.setVisible(true);
                
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBookButton;
    private javax.swing.JButton back;
    private javax.swing.JLabel booklabel;
    private javax.swing.JComboBox<String> combobooks;
    private javax.swing.JComboBox<String> combodepartement;
    private javax.swing.JTextField copiesfield;
    private javax.swing.JLabel copieslabel1;
    private javax.swing.JLabel departementlabel;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
