/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Entitites.Book;
import Entitites.Department;
import Entitites.Employee;
import Entitites.Library;
import Entitites.Supplier;
import Tables.*;
import static javax.swing.ListSelectionModel.SINGLE_SELECTION;

/**
 *
 * @author Raffy
 */
public class IndDepartment extends javax.swing.JFrame {

    String[] sNames = new String[Library.supplier.size()];
    int i;
    Department d;

    /**
     * Creates new form IndDepartment
     */
    public IndDepartment(int i) {
        initComponents();
        jComboBox1.setVisible(false);
        saveSupplierButton.setVisible(false);
        jComboBox2.setVisible(false);
        saveBookButton.setVisible(false);
jLabel5.setVisible(false);
        nameField.setVisible(false);
        idField.setVisible(false);
        emailField.setVisible(false);
        addressField.setVisible(false);
        positionField.setVisible(false);
        salaryField.setVisible(false);
        namelabel.setVisible(false);
         emaillabel.setVisible(false);
          idlabel.setVisible(false);
           addresslabel.setVisible(false);
            positionlabel.setVisible(false);
             salarylabel.setVisible(false);
             saveemployee.setVisible(false);
             jLabel7.setVisible(false);
          jLabel8.setVisible(false);   
jLabel1.setVisible(false);
jLabel7.setVisible(false);
deletelabel2.setVisible(false);
deletelabel1.setVisible(false);
  deletelabel.setVisible(false);
  addlabel.setVisible(false);
        setLocationRelativeTo(null);
        setResizable(false);
        this.i = i;
        d = Library.department.get(i);
        for (int j = 0; j < Library.supplier.size(); j++) {
            sNames[j] = Library.supplier.get(j).getName();
        }

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(sNames));
        jTable1.setSelectionMode(SINGLE_SELECTION);
        jTable2.setSelectionMode(SINGLE_SELECTION);
        jTable3.setSelectionMode(SINGLE_SELECTION);
        updateTable1(d);
        updateTable2(d);
        updateTable3(d);

        numberOfCopiesField.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        idField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        salaryField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        positionField = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        addemployee = new javax.swing.JButton();
        namelabel = new javax.swing.JLabel();
        idlabel = new javax.swing.JLabel();
        emaillabel = new javax.swing.JLabel();
        addresslabel = new javax.swing.JLabel();
        positionlabel = new javax.swing.JLabel();
        salarylabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        saveemployee = new javax.swing.JButton();
        saveemployee1 = new javax.swing.JButton();
        deleteemployee = new javax.swing.JButton();
        savelabel1 = new javax.swing.JLabel();
        deletelabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Home = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        addSupplierButton = new javax.swing.JButton();
        deletesupplier = new javax.swing.JButton();
        saveSupplierButton = new javax.swing.JButton();
        deletelabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        addbook = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        deletebook = new javax.swing.JButton();
        savebook1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        numberOfCopiesField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        saveBookButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        deletelabel1 = new javax.swing.JLabel();
        savelabel = new javax.swing.JLabel();
        addlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Add Supplier To Departement, Add Books To Departement & Add Employees To Departement");

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "ID", "Email", "Address", "Position", "Salary"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        addemployee.setText("Add");
        addemployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addemployeeActionPerformed(evt);
            }
        });

        namelabel.setText("Name");

        idlabel.setText("I.D");

        emaillabel.setText("Email");

        addresslabel.setText("Address");

        positionlabel.setText("Position");

        salarylabel.setText("Salary");

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Add Employees To Departement");

        saveemployee.setText("Save");
        saveemployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveemployeeActionPerformed(evt);
            }
        });

        saveemployee1.setText("Save Edits");
        saveemployee1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveemployee1ActionPerformed(evt);
            }
        });

        deleteemployee.setText("Delete");
        deleteemployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteemployeeActionPerformed(evt);
            }
        });

        savelabel1.setBackground(new java.awt.Color(0, 0, 204));
        savelabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        savelabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        savelabel1.setText("Please save edits ");

        deletelabel2.setBackground(new java.awt.Color(255, 51, 51));
        deletelabel2.setForeground(new java.awt.Color(255, 51, 51));
        deletelabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deletelabel2.setText("*Please select an Employee from the table");

        jLabel8.setBackground(new java.awt.Color(255, 51, 51));
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("*Please Fill All Fields");

        Home.setText("Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("*Please Enter A valid data");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(352, 352, 352))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(namelabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(emaillabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addresslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(positionlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salarylabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(positionField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salaryField)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(saveemployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(deleteemployee, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deletelabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addemployee, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(saveemployee1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(savelabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane3)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namelabel)
                    .addComponent(idlabel)
                    .addComponent(emaillabel)
                    .addComponent(addresslabel)
                    .addComponent(positionlabel)
                    .addComponent(salarylabel))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(positionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salaryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveemployee)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addemployee, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveemployee1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(savelabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteemployee, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletelabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Email", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        addSupplierButton.setText("Add");
        addSupplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSupplierButtonActionPerformed(evt);
            }
        });

        deletesupplier.setText("Delete");
        deletesupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletesupplierActionPerformed(evt);
            }
        });

        saveSupplierButton.setText("Save");
        saveSupplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveSupplierButtonActionPerformed(evt);
            }
        });

        deletelabel.setBackground(new java.awt.Color(255, 51, 51));
        deletelabel.setForeground(new java.awt.Color(255, 51, 51));
        deletelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deletelabel.setText("*Please select a supplier from the table");

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Add Supplier To Departement");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(addSupplierButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(saveSupplierButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deletesupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(saveSupplierButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(addSupplierButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(11, 11, 11)
                .addComponent(deletelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deletesupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Price", "Serial", "Number of Copies"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        addbook.setText("Add");
        addbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbookActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        deletebook.setText("Delete");
        deletebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebookActionPerformed(evt);
            }
        });

        savebook1.setText("Save Edits");
        savebook1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebook1ActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 51, 51));
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("*Please Enter No. Of Copies");

        jLabel5.setText("Enter No. Of Copies");

        saveBookButton.setText("Save");
        saveBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBookButtonActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Add Books To Departement");

        deletelabel1.setBackground(new java.awt.Color(255, 51, 51));
        deletelabel1.setForeground(new java.awt.Color(255, 51, 51));
        deletelabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deletelabel1.setText("*Please select a Book from the table");

        savelabel.setBackground(new java.awt.Color(0, 0, 204));
        savelabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        savelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        savelabel.setText("Please save edits ");

        addlabel.setForeground(new java.awt.Color(255, 0, 0));
        addlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addlabel.setText("*Please select a supplier from the table");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deletebook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(savebook1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deletelabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(125, 125, 125))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(addbook, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(numberOfCopiesField, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberOfCopiesField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveBookButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(addbook, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savebook1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deletebook, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletelabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void updateTable1(Department d, Supplier s) {
       TabelModel3 model = TableFunctions.updateSuppofDepTable(d, s);
       jTable1.setModel(model);
       Library.department.set(i, d);
   }

   void updateTable1(Department d) {
       TabelModel3 model = TableFunctions.updateSuppofDepTable(d);
       jTable1.setModel(model);
       Library.department.set(i, d);
   }

   void updateTable2(Department d) {
       TabelModel2 model = TableFunctions.updateBookofDepTable(d);
       jTable2.setModel(model);
       Library.department.set(i, d);
   }

   void updateTable2(Department d, Book b) {
       TabelModel2 model = TableFunctions.updateBookofDepTable(d, b);
       jTable2.setModel(model);
       Library.department.set(i, d);
   }

   void updateTable3(Department d) {
       TabelModel model = TableFunctions.updateEmpofDepTable(d);
       jTable3.setModel(model);
       Library.department.set(i, d);

   }

   void updateTable3(Department d, Employee e) {
       TabelModel model = TableFunctions.updateEmpofDepTable(d, e);
       jTable3.setModel(model);
       Library.department.set(i, d);

   }
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void addbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbookActionPerformed
int index=-1;
        index = jTable1.getSelectedRow();
        
        
               
        if (index >= 0) {
            String[] bNames = new String[d.supplier.get(index).book.size()];

        for (int j = 0; j < d.supplier.get(index).book.size(); j++) {
            bNames[j] = d.supplier.get(index).book.get(j).getName();
        }
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(bNames));
        jComboBox2.setVisible(true);
        saveBookButton.setVisible(true);
        numberOfCopiesField.setVisible(true);
        jLabel5.setVisible(true);
         addlabel.setVisible(false);
        }
        else addlabel.setVisible(true);        
        
// TODO add your handling code here:
    }//GEN-LAST:event_addbookActionPerformed

    private void saveSupplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveSupplierButtonActionPerformed
        int index = jComboBox1.getSelectedIndex();
        updateTable1(d, Library.supplier.get(index));
        jComboBox1.setVisible(false);
        saveSupplierButton.setVisible(false);
        deletelabel.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_saveSupplierButtonActionPerformed

    private void deletesupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletesupplierActionPerformed
int i=-1;
         i = jTable1.getSelectedRow();
        
        
               
        if (i >= 0) {
            d.deleteSupplier(i);
            updateTable1(d);
            deletelabel.setVisible(false);
        }
        else deletelabel.setVisible(true);       
                // TODO add your handling code here:
    }//GEN-LAST:event_deletesupplierActionPerformed

    private void addSupplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSupplierButtonActionPerformed
        jComboBox1.setVisible(true);
        saveSupplierButton.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_addSupplierButtonActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
jComboBox1.setVisible(false);
        saveSupplierButton.setVisible(false);
        jComboBox2.setVisible(false);
        saveBookButton.setVisible(false);
jLabel5.setVisible(false);
        nameField.setVisible(false);
        idField.setVisible(false);
        emailField.setVisible(false);
        addressField.setVisible(false);
        positionField.setVisible(false);
        salaryField.setVisible(false);
        namelabel.setVisible(false);
         emaillabel.setVisible(false);
          idlabel.setVisible(false);
           addresslabel.setVisible(false);
            positionlabel.setVisible(false);
             salarylabel.setVisible(false);
             saveemployee.setVisible(false);
             jLabel7.setVisible(false);
          jLabel8.setVisible(false);   
jLabel1.setVisible(false);
jLabel7.setVisible(false);
deletelabel2.setVisible(false);
deletelabel1.setVisible(false);
  deletelabel.setVisible(false);
  addlabel.setVisible(false); 
                Suppliers.D.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void saveBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBookButtonActionPerformed
        int bookIndex = jComboBox2.getSelectedIndex();
        int supplierIndex = jTable1.getSelectedRow();
        Book b = d.supplier.get(supplierIndex).book.get(bookIndex);
if (numberOfCopiesField.getText() == null ||numberOfCopiesField.getText().equals("") )
{
             int numberOfCopies = 1;
       
        b.setNumberOfCopies(numberOfCopies);
        updateTable2(d, b);
        jComboBox2.setVisible(false);
        saveBookButton.setVisible(false);
        numberOfCopiesField.setVisible(false);
        jLabel5.setVisible(false);
        jLabel7.setVisible(false);
            }
 
        else if (Suppliers.check(numberOfCopiesField.getText()))
            {
                int numberOfCopies = Integer.parseInt(numberOfCopiesField.getText());
       
        b.setNumberOfCopies(numberOfCopies);
        updateTable2(d, b);
        jComboBox2.setVisible(false);
        saveBookButton.setVisible(false);
        numberOfCopiesField.setVisible(false);
        
        jLabel7.setVisible(false);
        jLabel5.setVisible(false);
            }
            else jLabel7.setVisible(true);
        
        
       
// TODO add your handling code here:
    }//GEN-LAST:event_saveBookButtonActionPerformed

    private void savebook1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebook1ActionPerformed
        Book b = null;

        String name;
        String serial;
        float price;
        int numberOfCopies;

        d.deleteAllBooks();

        for (int i = 0; i < jTable2.getRowCount(); i++) {

            name = (String) jTable2.getValueAt(i, 0);
            price = (float) jTable2.getValueAt(i, 1);
            serial = (String) jTable2.getValueAt(i, 2);
            numberOfCopies = (int) jTable2.getValueAt(i, 3);
            b = new Book(name, serial, price, numberOfCopies);

            d.addBook(b);

        }
        if (b != null) {
            updateTable2(d);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_savebook1ActionPerformed

    private void deletebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebookActionPerformed
int i=-1;
         i = jTable2.getSelectedRow();
        
        
               
        if (i >= 0) { d.deleteBook(i);
            updateTable2(d);
           
            deletelabel1.setVisible(false);
        }
        else deletelabel1.setVisible(true);        
           
               // TODO add your handling code here:
    }//GEN-LAST:event_deletebookActionPerformed

    private void addemployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addemployeeActionPerformed
      nameField.setVisible(true);
        idField.setVisible(true);
        emailField.setVisible(true);
        addressField.setVisible(true);
        positionField.setVisible(true);
        salaryField.setVisible(true);   
         namelabel.setVisible(true);
         emaillabel.setVisible(true);
          idlabel.setVisible(true);
           addresslabel.setVisible(true);
            positionlabel.setVisible(true);
             salarylabel.setVisible(true);
             saveemployee.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_addemployeeActionPerformed

    private void saveemployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveemployeeActionPerformed

        Employee e;
        String name = nameField.getText();
        String id = idField.getText();
        String email = emailField.getText();
        String address = addressField.getText();
        String position = positionField.getText();
        String strSalary = salaryField.getText();
        if (name == null ||name.equals("")||id  == null ||id .equals("")||email == null ||email.equals("")||address == null ||address.equals("")||position  == null ||position .equals("")||strSalary == null ||strSalary.equals("")) 
        {
             jLabel8.setVisible(true);
            }
 
        else if (Suppliers.check(strSalary))
            {
               float salary = Float.parseFloat(strSalary);
               e = new Employee(name, id, email, address, position, salary);
        updateTable3(d, e);

        nameField.setText("");
        idField.setText("");
        emailField.setText("");
        addressField.setText("");
        positionField.setText("");
        salaryField.setText("");

        nameField.setVisible(false);
        idField.setVisible(false);
        emailField.setVisible(false);
        addressField.setVisible(false);
        positionField.setVisible(false);
        salaryField.setVisible(false); 
         namelabel.setVisible(false);
         emaillabel.setVisible(false);
          idlabel.setVisible(false);
           addresslabel.setVisible(false);
            positionlabel.setVisible(false);
             salarylabel.setVisible(false);
             saveemployee.setVisible(false);
             jLabel1.setVisible(false);
        jLabel8.setVisible(false);
            }
            else jLabel1.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_saveemployeeActionPerformed

    private void saveemployee1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveemployee1ActionPerformed
        Employee e = null;

        String name;
        String id;
        String email;
        String address;
        String position;
        float salary;

        d.deleteAllEmployees();

        for (int i = 0; i < jTable3.getRowCount(); i++) {

            name = (String) jTable3.getValueAt(i, 0);
            id = (String) jTable3.getValueAt(i, 1);
            email = (String) jTable3.getValueAt(i, 2);
            address = (String) jTable3.getValueAt(i, 3);
            position = (String) jTable3.getValueAt(i, 4);
            salary = (float) jTable3.getValueAt(i, 5);

            e = new Employee(name, id, email, address, position, salary);

            d.addEmployee(e);

        }
        if (e != null) {
            updateTable3(d);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_saveemployee1ActionPerformed

    private void deleteemployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteemployeeActionPerformed
     int i=-1;
         i = jTable3.getSelectedRow();
        
        
               
        if (i >= 0) {d.deleteEmployee(i);
            updateTable3(d);  
           
            deletelabel2.setVisible(false);
        }
        else deletelabel2.setVisible(true);   
        
                  // TODO add your handling code here:
    }//GEN-LAST:event_deleteemployeeActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
jComboBox1.setVisible(false);
        saveSupplierButton.setVisible(false);
        jComboBox2.setVisible(false);
        saveBookButton.setVisible(false);
jLabel5.setVisible(false);
        nameField.setVisible(false);
        idField.setVisible(false);
        emailField.setVisible(false);
        addressField.setVisible(false);
        positionField.setVisible(false);
        salaryField.setVisible(false);
        namelabel.setVisible(false);
         emaillabel.setVisible(false);
          idlabel.setVisible(false);
           addresslabel.setVisible(false);
            positionlabel.setVisible(false);
             salarylabel.setVisible(false);
             saveemployee.setVisible(false);
             jLabel7.setVisible(false);
          jLabel8.setVisible(false);   
jLabel1.setVisible(false);
jLabel7.setVisible(false);
deletelabel2.setVisible(false);
deletelabel1.setVisible(false);
  deletelabel.setVisible(false);
  addlabel.setVisible(false);
  Suppliers.h.setVisible(true);
dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_HomeActionPerformed
    
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Home;
    private javax.swing.JButton addSupplierButton;
    private javax.swing.JButton addbook;
    private javax.swing.JButton addemployee;
    private javax.swing.JLabel addlabel;
    private javax.swing.JTextField addressField;
    private javax.swing.JLabel addresslabel;
    private javax.swing.JButton back;
    private javax.swing.JButton deletebook;
    private javax.swing.JButton deleteemployee;
    private javax.swing.JLabel deletelabel;
    private javax.swing.JLabel deletelabel1;
    private javax.swing.JLabel deletelabel2;
    private javax.swing.JButton deletesupplier;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emaillabel;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel idlabel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel namelabel;
    private javax.swing.JTextField numberOfCopiesField;
    private javax.swing.JTextField positionField;
    private javax.swing.JLabel positionlabel;
    private javax.swing.JTextField salaryField;
    private javax.swing.JLabel salarylabel;
    private javax.swing.JButton saveBookButton;
    private javax.swing.JButton saveSupplierButton;
    private javax.swing.JButton savebook1;
    private javax.swing.JButton saveemployee;
    private javax.swing.JButton saveemployee1;
    private javax.swing.JLabel savelabel;
    private javax.swing.JLabel savelabel1;
    // End of variables declaration//GEN-END:variables
}
